### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by jobhh** [datalogic/datalogic-android-sdk-selfshopping#1]
I added jitpack to the proper place and following lines to the build.gradle file:

    implementation 'com.github.datalogic:datalogic-android-sdk:1.15'
    implementation 'com.github.datalogic:datalogic-android-sdk-selfshopping:1.8'

This is the error when building:

    Android resource linking failed 
    PROJECTDIR\build\intermediates\merged_manifests\datalogicDebug\AndroidManifest.xml:18: error: unexpected element <uses-library> found in <manifest>.

I checked the merged manifests. It has one of the two `<uses-library>` in the wrong location. The `<uses-library>` from the regular datalogic-android-sdk is placed properly within the `<application>` section. But the one from datalogic-android-sdk-selfshopping is placed before the `<application>` section.

This is a global overview of the merged manifest:

    <manifest ... >
        <uses-sdk ... />
        ...
        <uses-library
                    android:name="com.datalogic.extension.selfshopping"
                    android:required="true" />
        ...
        <application ... >
            <service ... />
            <activity ... >
                ...
            </activity>

            ...
            ...
            <uses-library
                        android:name="com.datalogic.device"
                        android:required="false" />
            ...
            ...
        </application>
    </manifest>

While using these I have no `<uses-library>` in my regular manifests, so these are both imported from these github libraries. I'm not quite sure why this is happening.

Soooo, for now I'll place the regular `<uses-library>`'s back in the manifest and us the regular SDK :)

**Comment by codybrookshear** [comment]
Hi, 
Yes, I inserted the `<uses-library>` tag in the wrong place in the manifest in version 1.8. I pushed version 1.8a shortly thereafter fixing that. try this:

```
implementation 'com.github.datalogic:datalogic-android-sdk-selfshopping:1.8a'
```
I went ahead an updated the README.md to describe using `v1.8a`.

Cody

**Comment by jobhh** [comment]
That does explain why I didn't find anything wrong with the code on github :) Thanks! Next time I'll check releases for the lastest version.
