### ISSUE TITLE
Error: Program type already present

### ISSUE THREAD

**Issue by jobhh** [datalogic/datalogic-android-sdk-selfshopping#2]
When using both datalogic-android-sdk:1.16 and datalogic-android-sdk-selfshopping:1.8a via gradle imports it produces the following error during a build:

    Error: Program type already present: com.datalogic.android.sdk.BuildConfig

The same name is used in the AndroidManifest.xml files, which both contain `<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.datalogic.android.sdk">`, and the build.gradle files, which both contain `group='com.github.datalogic'`.

**Comment by codybrookshear** [comment]
Hi @jobhh 

Thank you for pointing out this issue. I have made the needed change [here](https://github.com/datalogic/datalogic-android-sdk-selfshopping/commit/ea9aaea3eff215ccce8a150ded47a04e22ade0e3).

Please try with `com.github.datalogic:datalogic-android-sdk-selfshopping:v1.8b`

Thank you,
Cody Brookshear

**Comment by jobhh** [comment]
Hey Cody,

That seems to work, thanks :)

Kind regards,
Job

**Comment by codybrookshear** [comment]
@jobhh you had asked this question a while back:

> Additional question: Do you know if it possible to disable (and hide) the power button via the Datalogic SDK?
> We intent to use the Datalogic devices in a Kiosk-like fashion. As device owner we can enable lock task mode to force the user into our kiosk app and remove the home and multitask buttons, but the power button remains active.
> I haven't found power button related information in the documentation, but maybe I missed something.
https://datalogic.github.io/android-sdk-docs/reference/packages.html
https://datalogic.github.io/android-sdk-extension-selfshopping-docs/reference/packages.html

I (finally) have a response for you. In Joya Touch A6 and Memor1 devices you can hide Navigation bar in two different ways:

1. enable or disable the navigation bar through the developer options settings;
2. enable or disable the navigation bar programmatically with the method:
  Settings.System.putInt(getContentResolver(), "dev_force_show_navbar", 0); // disable
  Settings.System.putInt(getContentResolver(), "dev_force_show_navbar", 1); // enable
  You will also need to use the WRITE_SETTINGS permission in the manifest.
